name: TSMCNetworkTools
version: 1.2.6
main: me.thesquadmc.Main
author: ckamps
depend: [LuckPerms]

commands:
    adminchat:
        aliases: [ac, a, achat]
    find:
        aliases: [whereis, locate, findplayer, locateplayer, findp, locatep]
    freeze:
    freezepanel:
    invsee:
        aliases: [invc]
    lookup:
        aliases: [check]
    managerchat:
        aliases: [mc]
    randomtp:
        aliases: [rtp]
    staffchat:
        aliases: [sc, schat]
    staffmode:
        aliases: [mod]
    staff:
        aliases: [onlinestaff, liststaff, online, onlineplayers, list, listplayers, eonline, elist]
    stp:
    unfreeze:
    vanish:
        aliases: [v, iv]
    xray:
    report:
        aliases: [reporthacks]
    managereports:
        aliases: [reports]
    alert:
        aliases: [global, announce]
    stop:
    whitelist:
        aliases: [wl]
    launch:
    forcefield:
        aliases: [ff]
    ytvanish:
    staffmenu:
    monitor:
        aliases: [monitorreport]
    ytnick:
    disguiseplayer:
        aliases: [displayer]
    undisguiseplayer:
        aliases: [undisplayer]
    silence:
    slowchat:
        aliases: [delay, delaychat]
    smite:
        aliases: [lightning]
    ping:
    status:
    proxytransport:
        aliases: [pt, ptransport, takemethere]
    restarttime:
    apply:
    discord:
    store:
    website:
    uniqueplayers:
    title:
    queuerestart:
    vanishlist:
        aliases: [vlist]
    ntversion:
    mg:
    staffalert:
    onlinecount:
        aliases: [oc]
    logs:
        aliases: [chatlogs, clogs]
    l1:
    l2:
    party:
    motdclear:
    rename:
    giveall:
    firework:
    setplayers:
